title: Carl Delfin
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carldelfin.github.io"
twitter_username: jekyllrb
github_username:  carldelfin

# Build settings
remote_theme: chesterhow/tale
permalink:    /:year-:month-:day/:title
paginate:     5
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Carl Delfin 
  url:          https://carldelfin.github.io
  email:        carldelfin@pm.me 

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
